---
cluster:
  hosts:
    pybr25-rondonit.tangrama.com.br:
      ansible_user: root
      ansible_host: pybr25-rondonit.tangrama.com.br
      host: pybr25-rondonit
      hostname: pybr25-rondonit.tangrama.com.br
      swarm_node:
        labels:
          type: manager
          env: production

  children:
    cluster_managers:
      children:
        cluster_manager:
          hosts:
            pybr25-rondonit.tangrama.com.br:

        cluster_managers_additional:
          hosts:

    cluster_workers:
      hosts:
