---
version: '3.9'

services:
  swarm-cronjob:
    image: "ghcr.io/crazy-max/swarm-cronjob:${CRONJOB_VERSION}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=${TZ}"
      - "LOG_LEVEL=${LOG_LEVEL}"
      - "LOG_JSON=${LOG_JSON}"
    deploy:
      placement:
        constraints:
          - node.role == manager
