name: Backend CI

on:
  workflow_call:
    inputs:
      base-tag:
        required: true
        type: string
      image-name-prefix:
        required: true
        type: string
      image-name-suffix:
        required: true
        type: string
      python-version:
        required: true
        type: string
      plone-version:
        required: true
        type: string
      working-directory:
        required: false
        type: string
        default: backend

jobs:

  lint:
    name: "Backend: Lint"
    uses: plone/meta/.github/workflows/backend-lint.yml@2.x
    with:
      python-version: ${{ inputs.python-version }}
      plone-version: ${{ inputs.plone-version }}
      working-directory: ${{ inputs.working-directory }}

  test:
    name: "Backend: Test"
    uses: plone/meta/.github/workflows/backend-pytest.yml@2.x
    with:
      python-version: ${{ inputs.python-version }}
      plone-version: ${{ inputs.plone-version }}
      working-directory: ${{ inputs.working-directory }}

  coverage:
    name: "Backend: Coverage"
    uses: plone/meta/.github/workflows/backend-pytest-coverage.yml@2.x
    with:
      python-version: ${{ inputs.python-version }}
      plone-version: ${{ inputs.plone-version }}
      working-directory: ${{ inputs.working-directory }}

  release:
    name: "Backend: Build and publish Container Image"
    uses: plone/meta/.github/workflows/container-image-build-push.yml@2.x
    needs:
      - lint
      - test
      - coverage
    permissions:
      contents: read
      packages: write
    with:
      base-tag: ${{ inputs.base-tag }}
      image-name-prefix: ${{ inputs.image-name-prefix }}
      image-name-suffix: ${{ inputs.image-name-suffix }}
      working-directory: ${{ inputs.working-directory }}
      build-args: |
        PLONE_VERSION=${{ inputs.plone-version }}
      push: ${{ github.event_name != 'pull_request' }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  report:
    name: "Final report"
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - coverage
      - release
    steps:
      - name: Write report
        run: |
          echo '# Backend Workflow Report' >> $GITHUB_STEP_SUMMARY
          echo '| Job ID | Conclusion |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo '| lint | ${{ needs.lint.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| test | ${{ needs.test.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| coverage | ${{ needs.coverage.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| release | ${{ needs.release.result }} |' >> $GITHUB_STEP_SUMMARY
