name: "Compute Config variables"

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "24"
      python-version:
        required: false
        type: string
        default: "3.12"
      stack-name:
        required: false
        type: string
        default: "pybr25-rondonit-tangrama-com-br"
      environment:
        required: false
        type: string
        default: "pybr25-rondonit.tangrama.com.br"
    outputs:
      acceptance:
        description: "Flag reporting if we should run the acceptance jobs"
        value: ${{ jobs.config.outputs.acceptance }}
      backend:
        description: "Flag reporting if we should run the backend jobs"
        value: ${{ jobs.config.outputs.backend }}
      devops:
        description: "Flag reporting if we should run the devops jobs"
        value: ${{ jobs.config.outputs.devops }}
      docs:
        description: "Flag reporting if we should run the docs jobs"
        value: ${{ jobs.config.outputs.docs }}
      frontend:
        description: "Flag reporting if we should run the frontend jobs"
        value: ${{ jobs.config.outputs.frontend }}
      varnish:
        description: "Flag reporting if we should run the varnish jobs"
        value: ${{ jobs.config.outputs.varnish }}
      base-tag:
        description: "Base tag to be used when creating container images"
        value: ${{ jobs.config.outputs.base-tag }}
      event-name:
        description: "Event name triggering the workflow"
        value: ${{ github.event_name }}
      image-name-prefix:
        description: "Image name prefix for container images"
        value: ${{ jobs.config.outputs.image-name-prefix }}
      stack-name:
        description: "Stack name for the deployment"
        value: ${{ inputs.stack-name }}
      environment:
        description: "Environment to be used for the deployment"
        value: ${{ inputs.environment }}
      node-version:
        description: "Node version to be used"
        value: ${{ inputs.node-version }}
      python-version:
        description: "Python version to be used"
        value: ${{ inputs.python-version }}
      plone-version:
        description: "Plone version to be used"
        value: ${{ jobs.config.outputs.plone-version }}
      volto-version:
        description: "Volto version to be used"
        value: ${{ jobs.config.outputs.volto-version }}

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      acceptance: ${{ steps.filter.outputs.acceptance }}
      backend: ${{ steps.filter.outputs.backend }}
      devops: ${{ steps.filter.outputs.devops }}
      docs: ${{ steps.filter.outputs.docs }}
      frontend: ${{ steps.filter.outputs.frontend }}
      varnish: ${{ steps.filter.outputs.varnish }}
      base-tag: ${{ steps.vars.outputs.base-tag }}
      plone-version: ${{ steps.vars.outputs.plone-version }}
      volto-version: ${{ steps.vars.outputs.volto-version }}
      image-name-prefix: ${{ steps.vars.outputs.image-name-prefix }}

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup uv
        uses: plone/meta/.github/actions/setup_uv@2.x
        with:
          python-version: ${{ inputs.python-version }}
          working-directory: '.'

      - name: Compute several vars needed for the CI
        id: vars
        shell: bash
        run: |
          REPOSITORY_SETTINGS="$(uvx repoplone settings dump)"
          echo "image-name-prefix=$(jq -r '.container_images_prefix' <<< "$REPOSITORY_SETTINGS")" >> "$GITHUB_OUTPUT"
          echo "plone-version=$(jq -r '.backend.base_package_version' <<< "$REPOSITORY_SETTINGS")" >> "$GITHUB_OUTPUT"
          echo "volto-version=$(jq -r '.frontend.volto_version' <<< "$REPOSITORY_SETTINGS")" >> "$GITHUB_OUTPUT"
          echo "base-tag=sha-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Filter paths
        uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            acceptance:
              - '.github/workflows/backend*'
              - '.github/workflows/frontend*'
              - '.github/workflows/config*'
              - 'backend/**'
              - 'frontend/**'
            backend:
              - 'backend/**'
              - '.github/workflows/backend*'
              - '.github/workflows/config*'
            devops:
              - 'devops/**'
              - '.github/workflows/config*'
            docs:
              - '.readthedocs.yaml'
              - 'docs/**'
              - '.github/workflows/docs.yaml'
              - '.github/workflows/config*'
            frontend:
              - 'frontend/**'
              - '.github/workflows/frontend*'
              - '.github/workflows/config*'
            varnish:
              - 'devops/varnish/**'
              - '.github/workflows/varnish*'
              - '.github/workflows/config*'

      - name: Test vars
        run: |
          echo '# Config Settings' >> $GITHUB_STEP_SUMMARY
          echo '| Variable | Value |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo "| base-tag | ${{ steps.vars.outputs.base-tag }} |" >> $GITHUB_STEP_SUMMARY
          echo "| plone-version | ${{ steps.vars.outputs.plone-version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| volto-version | ${{ steps.vars.outputs.volto-version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| image-name-prefix | ${{ steps.vars.outputs.image-name-prefix }} |" >> $GITHUB_STEP_SUMMARY
          echo "| event-name | ${{ github.event_name }} |" >> $GITHUB_STEP_SUMMARY
          echo "| acceptance | ${{ steps.filter.outputs.acceptance }} |" >> $GITHUB_STEP_SUMMARY
          echo "| backend | ${{ steps.filter.outputs.backend }} |" >> $GITHUB_STEP_SUMMARY
          echo "| devops | ${{ steps.filter.outputs.devops }} |" >> $GITHUB_STEP_SUMMARY
          echo "| docs | ${{ steps.filter.outputs.docs }} |" >> $GITHUB_STEP_SUMMARY
          echo "| frontend | ${{ steps.filter.outputs.frontend }} |" >> $GITHUB_STEP_SUMMARY
          echo "| varnish | ${{ steps.filter.outputs.varnish }} |" >> $GITHUB_STEP_SUMMARY
