name: Tutorial Python Brasil CI

on:
  push:
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/*.yml"
      - "docs/**"
      - .readthedocs.yaml
      - "devops/**"
  workflow_dispatch:

jobs:
  config:
    uses: ./.github/workflows/config.yml

  backend:
    uses: ./.github/workflows/backend.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: backend
        python-version: ${{ needs.config.outputs.python-version }}
        plone-version: ${{ needs.config.outputs.plone-version }}
    if: ${{ needs.config.outputs.backend == 'true' }}
    permissions:
      contents: read
      packages: write

  docs:
    uses: ./.github/workflows/docs.yml
    needs:
        - config
    with:
        python-version: ${{ needs.config.outputs.python-version }}
        working-directory: docs
    if: ${{ needs.config.outputs.docs == 'true' }}

  frontend:
    uses: ./.github/workflows/frontend.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: frontend
        node-version: ${{ needs.config.outputs.node-version }}
        volto-version: ${{ needs.config.outputs.volto-version }}
    if: ${{ needs.config.outputs.frontend == 'true' }}
    permissions:
      contents: read
      packages: write

  varnish:
    uses: ./.github/workflows/varnish.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: varnish
    if: ${{ needs.config.outputs.varnish == 'true' }}
    permissions:
      contents: read
      packages: write

  report:
    name: "Final report"
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - config
      - backend
      - frontend
      - docs
      - varnish
    steps:
      - name: Write report
        run: |
          echo '# Workflow Report' >> $GITHUB_STEP_SUMMARY
          echo '| Job ID | Conclusion |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo '| config | ${{ needs.config.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| backend | ${{ needs.backend.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| docs | ${{ needs.docs.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| frontend | ${{ needs.frontend.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| varnish | ${{ needs.varnish.result }} |' >> $GITHUB_STEP_SUMMARY
